//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thoth.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas
    {
        public long Id { get; set; }
        public long EstudianteId { get; set; }
        public string EdadMatricula { get; set; }
        public string NumeroMatricula { get; set; }
        public string Numerofolio { get; set; }
        public System.DateTime FechaMatricula { get; set; }
        public System.DateTime AnioMatricula { get; set; }
        public long GradoId { get; set; }
        public long GrupoId { get; set; }
        public long JornadaId { get; set; }
        public long EstadoMatricula { get; set; }
        public bool Repitente { get; set; }
        public long TipoCaracterId { get; set; }
        public long SedeId { get; set; }
        public bool Observaciones { get; set; }
    
        public virtual EstadoEstudiantes EstadoEstudiantes { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Grados Grados { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Jornadas Jornadas { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual TipoCaracteres TipoCaracteres { get; set; }
    }
}
