//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thoth.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesores()
        {
            this.Cursos = new HashSet<Cursos>();
            this.Materias = new HashSet<Materias>();
        }
    
        public long Id { get; set; }
        public string Codigo { get; set; }
        public long TipoIdentificacionId { get; set; }
        public string NumeroDocumento { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public long ProfesionId { get; set; }
        public long EscalafonId { get; set; }
        public long SedeId { get; set; }
        public bool Activo { get; set; }
        public Nullable<long> UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<long> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public long GeneroId { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public long EstadoCivilId { get; set; }
        public int NumeroHijos { get; set; }
        public System.DateTime FechaVinculacion { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string LibretaMilitar { get; set; }
        public string ResolucionNombramiento { get; set; }
        public string FotoPerfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursos> Cursos { get; set; }
        public virtual Escalafones Escalafones { get; set; }
        public virtual EstadoCiviles EstadoCiviles { get; set; }
        public virtual Generos Generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materias> Materias { get; set; }
        public virtual Profesiones Profesiones { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual TipoIdentificaciones TipoIdentificaciones { get; set; }
    }
}
